POST http://radarlights:5005/api/notifications/message
Content-Type: application/json

{
    "message": "Hello... This is a test notification from LedMatrixOS!",
    "color": {
        "R": 150,
        "G": 0,
        "B": 255
    }
}
